# Generated by Django 5.0.2 on 2024-02-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='slide',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
