# Generated by Django 5.0.2 on 2024-02-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='order',
        ),
    ]
