# Generated by Django 5.0.2 on 2024-02-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_alter_slide_options_alter_slide_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ('order',)},
        ),
    ]
