# Generated by Django 5.0.2 on 2024-02-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_alter_url_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='background_image',
            field=models.ImageField(default='presentation-background-1.jpg', upload_to='background_image'),
        ),
    ]
