# Generated by Django 5.0.2 on 2024-02-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0003_alter_slide_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
