# Generated by Django 5.0.2 on 2024-02-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0005_alter_slide_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='presentation',
            name='order',
            field=models.PositiveIntegerField(default=0, max_length=255),
        ),
    ]
