# Generated by Django 5.0.2 on 2024-02-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0006_alter_presentation_options_presentation_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={},
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='order',
        ),
    ]
