# Generated by Django 5.0.2 on 2024-02-29 19:29

from django.db import migrations, models

def reorder(apps, schema_editor):
    MyModel = apps.get_model("presentation", "Slide")
    for order, item in enumerate(MyModel.objects.all(), 1):
        item.my_order = order
        item.save(update_fields=['order'])

class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0007_alter_presentation_options_remove_presentation_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(reorder, reverse_code=migrations.RunPython.noop),
    ]
