# Generated by Django 5.0 on 2024-01-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
